### ISSUE TITLE
Treated Crafting Table Dupe Bug

### ISSUE THREAD

**Issue by yigitabi5444** [stfwi/engineers-decor#138]
Version: 1.12.2
İf two people try to take crafted items from the treated crafting table, the items can occasionally be duped. if you take the items by shift clicking, it will always be duped.

**Comment by stfwi** [comment]
Hi, aye that needs some consideration ;)

**Comment by stfwi** [comment]
Just quickly, I did not forget about the issue, just have trouble reproducing that. Must be a sync issue.

**Comment by Tupilak** [comment]
I can still do the bug.
You need two player.
1. Make the recipie. Like 9 diamonds to make a block.
2. have the other player look into the table as well, and pull out the item.
3. The diamond is used, but the block is still there and you can pull it out.
4. If you have more the 4 in each slot, but only 1 diamond in one of them, and do step 1 - 3 again, then the diamonds is double, and you get a block as well.

**Comment by stfwi** [comment]
Hi, which mod version and MC version are you referring to? Cheers,-

**Comment by Tupilak** [comment]
Ohh sorry. I am playing modpack ATM6 v 1.5.2 (Latest at this writing) Engineers Decor is in v. 1.1.7

**Comment by stfwi** [comment]
I just pushed engineersdecor-1.16.4-1.1.8-b2 with an additional explicit sync when the crafting table inventory is changed.
As I currently do not have a remote server that causes lags or latencies, could you take a look if that resolved the problem for your setup and gimme quick feedback if ok or still wonky? Cheers!

**Comment by Tupilak** [comment]
No still have the problem.
I play on my owen lan game, so lag is not the problem. We have testet on the 1.1.8-b2 on all instalation.

**Comment by Tupilak** [comment]
Hey srfwi

I have a small video showing the problem. We are starting out with 36 iron ingot in the crafting table.
This is MC 1.16.5 with the Engineers Decor 1.1.8-b2 and JEI installed on Forge v. 36.042

https://www.dropbox.com/s/4d2avzh1qfgq7gx/Minecraft_Engineers_Decor.mp4?dl=0

**Comment by stfwi** [comment]
Hi, tupilak, ty for that video. Ya that's definitely easier than mining and cooking iron ;). So, I need to trace some deeper into the matter. In the worst case have to drop the vanilla crafting/sync part and do that myself. Could also be that other mods may have an influence using hooks or mixins, but I doubt that. Cheers!

**Comment by stfwi** [comment]
Hi, quick update, I made a change to handle the crafting result slot completely in the mod and include it in the sync for players around. It seems ok now, if you like to double check on your LAN setup, here's the "pre-release" (the jar is signed off by me):
[engineersdecor-1.16.4-1.1.8-b3t.zip](https://github.com/stfwi/engineers-decor/files/6045447/engineersdecor-1.16.4-1.1.8-b3t.zip).

**Comment by Tupilak** [comment]
Hey. I got to test this b3 out today. It works fine. We can no longer do the dublication, and also the table seen more fluid now. The other was it was some what glitchy.
Thanks for the fix

**Comment by stfwi** [comment]
Perfect that, thanks for double checking. Cheers,-
