### ISSUE TITLE
[1.16.5] Block placer doesn't place blocks, they pop as an item

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#193]
https://github.com/stfwi/engineers-decor/issues/179

engineersdecor-1.16.5-1.1.15
forge-1.16.5-36.2.16

![image](https://user-images.githubusercontent.com/4427684/143497242-bc3147b2-91c7-4e4d-859b-5e3067e16114.png)

**Comment by ProsperCraft** [comment]
![image](https://user-images.githubusercontent.com/4427684/143497312-900be0ac-8510-4a30-829b-1b4f3f30d7f6.png)

**Comment by stfwi** [comment]
Hi man, oops, regression, let's see what I messed up there ;)

**Comment by MuteTiefling** [comment]
Currently seeing this in all non overworld dimensions in Enigmatica 6 (tested in Nether and Atum). Works fine in the Overworld. 

Same version: engineersdecor-1.16.5-1.1.15

**Comment by stfwi** [comment]
Oky, I pushed a RB fix on Curse (`v1.1.16-b1`), but could not test in different dimensions. 
Could you check this version out and quickly write if the problem is gone? Cheers,-

**Comment by MuteTiefling** [comment]
Unfortunately, still seeing the same issue:
https://streamable.com/6ceukw

**Comment by stfwi** [comment]
Hi, finally got the time to tackle this in depth. It's a cross compat issue related to the block placement via their items. I modified it now in the way that the normal placement state is used when this "item usage" fails. 
The fix version is pushed to Curse and in approval: `engineersdecor-1.16.5-1.1.16-b2.jar`.
Cheers guys/girls for reaching out!

**Comment by stfwi** [comment]
Hi, oky just got the confirmation from #197 that the bug is gone now, I'll also close this issue then. Cheers!
